### ISSUE TITLE
Configure error

### ISSUE THREAD

**Issue by JiaGengChang** [mhekkel/mrc#2]
Steps to reproduce (follow the exact same steps as README.md):

```
git clone https://github.com/mhekkel/mrc.git
cd mrc
mkdir build
cd build
cmake ..
cmake --install
```
(The last line of above instructions is incomplete as it is missing output directory. I assume it is the current working directory, i.e. `.` or `""`)
So it should be
`cmake --install .`
or equivalently
`cmake --install ""`

**Comment by JiaGengChang** [comment]
Instead of using:
`cmake --install ""` or `cmake --install .`

I used:
`cmake --install "" --prefix=$CONDA_PREFIX`

and it works now.
Should add that this is because I do not have root permission, and I am building this from a conda environment.

**Comment by mhekkel** [comment]
Hi,

Thanks for reporting this issue. I must admit I'm a bit new to cmake.

That said, if you want to build software with cmake with the intention 
to install it somewhere else than the default location, you should 
perhaps use the CMAKE_INSTALL_PREFIX variable at the configure phase:


cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
cmake --build . --config Release
cmake --install . -C Release

Using an explicit name for the config tackles that other error as well.

-maarten

Op 2-9-2021 om 19:04 schreef Jia Geng Chang:
