### ISSUE TITLE
Following install instructions gives error

### ISSUE THREAD

**Issue by tkella47** [mhekkel/mrc#3]
The install instructions are incomplete, but looking at the previous issue ticket, trying to use cmake --build . --config Release throws undeclared identifier errors.

**Comment by mhekkel** [comment]
Could you please provide a little more details? Like what OS you're trying to install on, and perhaps the output on screen, an copy of the error messages?

Thanks in advance.

**Comment by tkella47** [comment]
Followed instructions to cmake --build . 
cmake version 3.22.1
macOS Monterey v 12.1
<img width="1213" alt="Screen Shot 2022-01-18 at 3 00 27 PM" src="https://user-images.githubusercontent.com/46170696/150009799-b53f8833-4099-4675-89bd-a3d4356604ac.png">

**Comment by tkella47** [comment]
I did a little more research and found that elf.h is not present on the Mac OS systems.
https://gist.github.com/mlafeldt/3885346 here is a release I moved into the correct folder. 
Now I am getting a different error
<img width="522" alt="Screen Shot 2022-01-18 at 4 59 25 PM" src="https://user-images.githubusercontent.com/46170696/150025554-48a9da1b-9f0e-45f7-b4d0-9a21a4632299.png">

**Comment by tkella47** [comment]
I may just install this on a linux system instead.

**Comment by mhekkel** [comment]
I'm sorry, the readme should have been more clear. mrc is not meant to be used on MacOS X. I'll add an extra check in the cmake file to warn about this.
