### ISSUE TITLE
Some questions :)

### ISSUE THREAD

**Issue by cpsauer** [mhekkel/mrc#5]
@mhekkel, you've got me curious: Which OS was the original? Would love to read up more on the history of resource compilers?

(Also curious: This doesn't work on macOS/mach-O does it? Asking because I think it'd be pretty cool to be able to run this cross-platform, under Bazel, probably, for it's nice cross-platform code gen abilities, and thereby unify resource access.)

Thanks for making something cool and sharing it with the world!
Chris

**Comment by mhekkel** [comment]
Hi Chris, you must be younger than I am. :-)
The concept of resource 'forks' was introduced by the original MacOS back in the eighties. Files consisted of two forks, one was data and the other contained the resources. For many years this was unique to MacOS. This setup had the advantage that you could edit the resources as well using ResEdit. Later, Windows introduced resources in a way similar to what mrc does now: it stored the resources embedded in the executable as a separate blob.
Later, BeOS came up with a filesystem with an unlimited amount of forks and they also improved on the whole resource concept. My implementation looks more like the BeOS version at the API level and resembles Windows at the implementation level.
I'm using features available in the executable format, for ELF and COFF that is something that was easy to do. Unfortunately for you, I haven't had access to a real Mac for decades and thus I don't know if Mach-O supports this, I guess it will. Of course, it would be nice to go full cross platform. But I don't have the time to find out how to do it, nor do I want to invest money in Apple computers anymore (I've had over 20 of those and I now am convinced that was enough).

Hope this answers your question. Feel free to have a look at the code and implement the parts for Mach-O/MacOS yourself. If it works I'm perfectly happy to incorporate it into the main code base.

**Comment by cpsauer** [comment]
Thanks @mhekkel for such a nice and thoughtful reply. I really appreciate you passing the knowledge down. This was great on its own--and a great jumping off point for my continued reading. I wish we still had that, and like your effort here very much.

I don't need it for mac just yet, but I likely will at some point. Offhand, I'd be tempted to bootstrap the cross-platform support off of C/C++, going from resource -> source files --compiler--> object files, keeping things unified rather than going directly to per-platform object files. I'd be tempted also to leave the resource names as symbols (instead of strings) for simplicity and to let the linker strip out any that might be unused. Do you have thoughts on that design? Are there obvious shortcomings?

Again, thank you so much,
Chris

**Comment by mhekkel** [comment]
> I don't need it for mac just yet, but I likely will at some point. Offhand, I'd be tempted to bootstrap the cross-platform support off of C/C++, going from resource -> source files --compiler--> object files, keeping things unified rather than going directly to per-platform object files. I'd be tempted also to leave the resource names as symbols (instead of strings) for simplicity and to let the linker strip out any that might be unused. Do you have thoughts on that design? Are there obvious shortcomings?

What you want is something I believe GNOME does already.

Yes, there are shortcomings. In your approach, everything ends up in the code and static data sections, mrc uses its own section. Theoretically I could create a resource editor capable of manipulating that separate section (replace or edit resources), something that is not doable in your setup.
